kashkolk_online/urls.py
"""Defines URL patterns for learning logs."""

from django.urls import path
from . import views

app_name = 'kashkolk_online'

urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    
    # Topics page
    path('topics', views.topics, name='topics'),
    
    #Detail page for a single 
    path('topics/<int:topic_id>/',views.topic,name='topic'),
    
    #page for adding new topics
    path('new_topic', views.new_topic, name='new_topic'),
    
    #page for adding new topics for the entries
    path('new_entry/<int:topic_id>/',views.new_entry, name='new_entry'),
    
    #page for editting an existing entry
    path('edit_entry/<int:entry_id>/',views.edit_entry, name='edit_entry'),
    
    ]

kop/urls.py
from django.contrib import admin
from django.urls import path , include
from kashkolk_online import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #Home page
    path('',include('kashkolk_online.urls')),
    #users
    path('users',include('users.urls')),
]

users/urls.py
'''Defines URLs patterns for users'''

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'

urlpatterns = [
    #login page
    path('login/', LoginView.as_view(template_name = 'users/login.html'),
    name='login'),
    
    #logout url
    path('logout', views.logout_view, name='logout'),
    
    #Registeration Page
    path('register', views.register, name='register')
    
    
]

kashkolk_online/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    
    def __str__(self):
        """Return a string represntation of the model"""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic,on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        """Return a string representation of the model."""
        if len( self.text )> 50:
            return self.text[:50] + "..."
        else:
            return self.text 

users/models.py
from django.db import models

# Create your models here.

kashkolk_online/forms.py
from django import forms

from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    """a form for users to enter a new topics"""
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}
        
class EntryForm(forms.ModelForm):
    """a form for users to enter a new entry for topics""" 
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'clos':80})}
        
    
    
    

kashkolk_online/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    """The home page for Kashkolk Online"""
    return render(request,'kashkolk_online/index.html')
    
@login_required
def topics(request):
    """Show all topics"""
    topics = Topic.objects.order_by('date_added')
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    
    return render(request,'kashkolk_online/topics.html',context)

@login_required
def topic(request,topic_id):
    """Show a topic page with its entries"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    if topic.owner!= request.user:
        raise Http404
    context = {'topic':topic, 'entries':entries}
    return render(request,'kashkolk_online/topic.html',context)
    
@login_required    
def new_topic(request):
    """Add a new topic,, handle the form ,, and get, post methods"""
    if request.method != 'POST':
        # no data sumbettid; create a blank form
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('kashkolk_online:topics'))
            
    context = {'form':form }
    return render(request, 'kashkolk_online/new_topic.html', context)
    
@login_required    
def new_entry(request,topic_id):
    """Add new entry to a particular topic"""
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = EntryForm()
        
    else:
        # POST data submitted; process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('kashkolk_online:topic',
                args=[topic_id]))
                
    context = {'topic':topic,'form':form}
    return render(request,'kashkolk_online/new_entry.html',context)
    
@login_required    
def edit_entry(request,entry_id):
    """Editting an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('kashkolk_online:topic',
                args = [topic.id]))
                
    context = {'entry':entry, 'form':form, 'topic': topic}
    return render(request,'kashkolk_online              /edit_entry.html', context)
        
        
    
    
    
    
    
    
    
    
    
    
    
    
    

users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """log the user out"""
    logout(request)
    return HttpResponseRedirect(reverse('kashkolk_online:index'))
    
    
def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display a blank registeration form
        form = UserCreationForm ()
    else:
        form = UserCreationForm (data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to the hompage
            authenticated_user = authenticate(username = new_user.username,
                password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect( reverse('kashkolk_online:index'))
            
    context = {'form':form}
    return render(request,'users/register.html',context)



kashkolk_online/templates/kashkolk_online/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Kashkolk Online</title>
        
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        
    </head>
    
    <body>
<!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                    <a class="navbar-brand" href="{% url 'kashkolk_online:index' %}" style="font-family: 'Brush Script MT', cursive; font-size: 40px;">
                        Kashkolk Online
                    </a>
                    
                    
                </div>
                
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'kashkolk_online:topics' %}">Topics</a></li>
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a>Hello, {{ user.username }}.</a></li>
                            <li><a href="{% url 'users:logout' %}">log out</a></li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}">register</a></li>
                            <li><a href="{% url 'users:login' %}">log in</a></li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse -->
                
            </div>
        </nav>
        
        <div class="container">
            
            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </div> <!-- /container -->
        
    </body>
</html>

kashkolk_online/templates/kashkolk_online/edit_entry.html
{% extends 'kashkolk_online/base.html' %}

{% block content %}

<p><a href = "{% url 'kashkolk_online:topic' topic.id%}">{{topic}}</a></p>
<p>Edit Entry:</p>

<form action="{% url 'kashkolk_online:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">save changes</button>
</form>

{% endblock content %}

kashkolk_online/templates/kashkolk_online/index.html
{% extends "kashkolk_online/base.html" %}

{% block header %}
    <div class='jumbotron'>
        <h1>Track your learning.</h1>
    </div>
{% endblock header %}

{% block content %}

<h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Kashkol, and list the topics you're learning about.
</h2>
<h2>
    Whenever you learn something new about a topic, make an entry
    summarizing what you've learned.
</h2>

{% endblock content %}

kashkolk_online/templates/kashkolk_online/new_entry.html
{% extends 'kashkolk_online/base.html' %}

{% block content%}

<p><a href= "{% url 'kashkolk_online:topic' topic.id %} "> {{topic}}</a></p>

<p>Add new entry:</p>
<form action= "{% url 'kashkolk_online:new_entry' topic.id %}" method= 'post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add entry</button>
</form>

{%endblock content%}

kashkolk_online/templates/kashkolk_online/new_topic.html
{% extends "kashkolk_online/base.html" %}

{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'kashkolk_online:new_topic' %}" method='post'
        class="form">
    
        {% csrf_token %}
        {% bootstrap_form form %}
    
        {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}
    
    </form>
    
{% endblock content %}

kashkolk_online/templates/kashkolk_online/topic.html
{% extends 'kashkolk_online/base.html' %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
    <p>
        <a href="{% url 'kashkolk_online:new_entry' topic.id %}">add new entry</a>
    </p>
    
    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'kashkolk_online:edit_entry' entry.id %}">
                            edit entry</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
    </div> <!-- panel -->
    
    {% empty %}
        There are no entries for this topic yet.
    {% endfor %}
    
{% endblock content %}

kashkolk_online/templates/kashkolk_online/topics.html
{% extends "kashkolk_online/base.html" %}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'kashkolk_online:topic' topic.id %}">{{ topic }}</a>
                </h3>
            </li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
    
<h3><a href="{% url 'kashkolk_online:new_topic' %}">Add new topic</h3>

{% endblock content %}

users/templates/users/login.html
{% extends 'kashkolk_online/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        
        {% buttons %}
            <button name="submit" class="btn btn-primary">log in</button>
        {% endbuttons %}
        
        <input type="hidden" name="next" value="{% url 'kashkolk_online:index' %}" />
    </form>
    
{% endblock content %}


users/templates/users/register.html
{% extends 'kashkolk_online/base.html' %}

{% block content %}

<form method="post" action=" {% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'kashkolk_online:index' %}">
</form>

{% endblock content %}